version: '3.8'
services:
  chrysedgeportal:
    image: chryscloud/chrysedgeportal:0.0.8.5
    build: web/
    depends_on:
      - chrysedgeserver
      - redis
    ports:
      - "8905:8905"
    networks:
      - chrysnet
  chrysedgeserver:
    image: chryscloud/chrysedgeserver:0.0.8.5
    build: