
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: video_streaming.proto

package chrys_cloud_videostreaming_v1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Annotation messages
type AnnotateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceName       string        `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`                          // required: device name (required) identity of device
	RemoteStreamId   string        `protobuf:"bytes,2,opt,name=remote_stream_id,json=remoteStreamId,proto3" json:"remote_stream_id,omitempty"`            //optional: if associated with storage, the ID of Chrysalis Cloud deviceID
	Type             string        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                        // required: event type: e.g. moving, exit, entry, stopped, parked, ...
	StartTimestamp   int64         `protobuf:"varint,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`             //required: start of the event
	EndTimestamp     int64         `protobuf:"varint,5,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`                   // optional: event of the event
	ObjectType       string        `protobuf:"bytes,6,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`                          // optional: e.g. person, car, face, bag, roadsign,...
	ObjectId         string        `protobuf:"bytes,7,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`                                // optional: e.g. object id from the ML model
	ObjectTrackingId string        `protobuf:"bytes,8,opt,name=object_tracking_id,json=objectTrackingId,proto3" json:"object_tracking_id,omitempty"`      // optional: tracking id of the object
	Confidence       float64       `protobuf:"fixed64,9,opt,name=confidence,proto3" json:"confidence,omitempty"`                                          // confidence of inference [0-1.0]
	ObjectBoudingBox *BoudingBox   `protobuf:"bytes,10,opt,name=object_bouding_box,json=objectBoudingBox,proto3" json:"object_bouding_box,omitempty"`     // optional: object bounding box
	Location         *Location     `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`                                               // optional: object GEO location
	ObjectCoordinate *Coordinate   `protobuf:"bytes,12,opt,name=object_coordinate,json=objectCoordinate,proto3" json:"object_coordinate,omitempty"`       // optional: object coordinates within the image
	Mask             []*Coordinate `protobuf:"bytes,13,rep,name=mask,proto3" json:"mask,omitempty"`                                                       // optional" object mask (polygon)
	ObjectSignature  []float64     `protobuf:"fixed64,14,rep,packed,name=object_signature,json=objectSignature,proto3" json:"object_signature,omitempty"` // optional: signature of the detected item
	MlModel          string        `protobuf:"bytes,15,opt,name=ml_model,json=mlModel,proto3" json:"ml_model,omitempty"`                                  // optional: description of the module that generated this event
	MlModelVersion   string        `protobuf:"bytes,16,opt,name=ml_model_version,json=mlModelVersion,proto3" json:"ml_model_version,omitempty"`           // optional: version of the ML model
	Width            int32         `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`                                                    // optional: image width
	Height           int32         `protobuf:"varint,18,opt,name=height,proto3" json:"height,omitempty"`                                                  // optional: image height
	IsKeyframe       bool          `protobuf:"varint,19,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"`                        // optional: true/false if this annotation is from keyframe
	VideoType        string        `protobuf:"bytes,20,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`                            // optional: e.g. mp4 filename, live stream, ...
	OffsetTimestamp  int64         `protobuf:"varint,21,opt,name=offset_timestamp,json=offsetTimestamp,proto3" json:"offset_timestamp,omitempty"`         // optional: offset from the beginning
	OffsetDuration   int64         `protobuf:"varint,22,opt,name=offset_duration,json=offsetDuration,proto3" json:"offset_duration,omitempty"`            // optional: duration from the offset
	OffsetFrameId    int64         `protobuf:"varint,23,opt,name=offset_frame_id,json=offsetFrameId,proto3" json:"offset_frame_id,omitempty"`             // optional: frame id of the
	OffsetPacketId   int64         `protobuf:"varint,24,opt,name=offset_packet_id,json=offsetPacketId,proto3" json:"offset_packet_id,omitempty"`          // optional: offset of the packet
	// extending the event message meta data (optional)
	CustomMeta_1 string `protobuf:"bytes,25,opt,name=custom_meta_1,json=customMeta1,proto3" json:"custom_meta_1,omitempty"` // e.g. gender, hair, car model, ...
	CustomMeta_2 string `protobuf:"bytes,26,opt,name=custom_meta_2,json=customMeta2,proto3" json:"custom_meta_2,omitempty"`
	CustomMeta_3 string `protobuf:"bytes,27,opt,name=custom_meta_3,json=customMeta3,proto3" json:"custom_meta_3,omitempty"`
	CustomMeta_4 string `protobuf:"bytes,28,opt,name=custom_meta_4,json=customMeta4,proto3" json:"custom_meta_4,omitempty"`
	CustomMeta_5 string `protobuf:"bytes,29,opt,name=custom_meta_5,json=customMeta5,proto3" json:"custom_meta_5,omitempty"`
}

func (x *AnnotateRequest) Reset() {
	*x = AnnotateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_streaming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotateRequest) ProtoMessage() {}

func (x *AnnotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_streaming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotateRequest.ProtoReflect.Descriptor instead.
func (*AnnotateRequest) Descriptor() ([]byte, []int) {
	return file_video_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *AnnotateRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AnnotateRequest) GetRemoteStreamId() string {
	if x != nil {
		return x.RemoteStreamId
	}
	return ""
}

func (x *AnnotateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnnotateRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *AnnotateRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *AnnotateRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *AnnotateRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AnnotateRequest) GetObjectTrackingId() string {
	if x != nil {
		return x.ObjectTrackingId
	}
	return ""
}

func (x *AnnotateRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnnotateRequest) GetObjectBoudingBox() *BoudingBox {
	if x != nil {
		return x.ObjectBoudingBox
	}
	return nil
}

func (x *AnnotateRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AnnotateRequest) GetObjectCoordinate() *Coordinate {
	if x != nil {
		return x.ObjectCoordinate
	}
	return nil
}

func (x *AnnotateRequest) GetMask() []*Coordinate {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *AnnotateRequest) GetObjectSignature() []float64 {
	if x != nil {
		return x.ObjectSignature
	}
	return nil
}

func (x *AnnotateRequest) GetMlModel() string {
	if x != nil {
		return x.MlModel
	}
	return ""
}

func (x *AnnotateRequest) GetMlModelVersion() string {
	if x != nil {
		return x.MlModelVersion
	}
	return ""
}

func (x *AnnotateRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AnnotateRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AnnotateRequest) GetIsKeyframe() bool {
	if x != nil {
		return x.IsKeyframe
	}
	return false
}

func (x *AnnotateRequest) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

func (x *AnnotateRequest) GetOffsetTimestamp() int64 {
	if x != nil {
		return x.OffsetTimestamp
	}
	return 0
}

func (x *AnnotateRequest) GetOffsetDuration() int64 {
	if x != nil {
		return x.OffsetDuration
	}
	return 0
}

func (x *AnnotateRequest) GetOffsetFrameId() int64 {
	if x != nil {
		return x.OffsetFrameId
	}
	return 0
}

func (x *AnnotateRequest) GetOffsetPacketId() int64 {
	if x != nil {
		return x.OffsetPacketId
	}
	return 0
}

func (x *AnnotateRequest) GetCustomMeta_1() string {
	if x != nil {
		return x.CustomMeta_1
	}
	return ""
}

func (x *AnnotateRequest) GetCustomMeta_2() string {
	if x != nil {
		return x.CustomMeta_2
	}
	return ""
}

func (x *AnnotateRequest) GetCustomMeta_3() string {
	if x != nil {
		return x.CustomMeta_3
	}
	return ""
}

func (x *AnnotateRequest) GetCustomMeta_4() string {
	if x != nil {
		return x.CustomMeta_4
	}
	return ""
}

func (x *AnnotateRequest) GetCustomMeta_5() string {
	if x != nil {
		return x.CustomMeta_5
	}
	return ""
}

type AnnotateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceName     string `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	RemoteStreamId string `protobuf:"bytes,2,opt,name=remote_stream_id,json=remoteStreamId,proto3" json:"remote_stream_id,omitempty"`
	Type           string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StartTimestamp int64  `protobuf:"varint,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
}

func (x *AnnotateResponse) Reset() {
	*x = AnnotateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_streaming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotateResponse) ProtoMessage() {}

func (x *AnnotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_streaming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotateResponse.ProtoReflect.Descriptor instead.
func (*AnnotateResponse) Descriptor() ([]byte, []int) {
	return file_video_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *AnnotateResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AnnotateResponse) GetRemoteStreamId() string {
	if x != nil {
		return x.RemoteStreamId
	}
	return ""
}

func (x *AnnotateResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnnotateResponse) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"` // latitude
	Lon float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"` // longitude
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_streaming_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_video_streaming_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_video_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_streaming_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_video_streaming_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.